name: jagdgesellschaft-ai

services:

  # nginx
  web:
    image: nginx:stable
    container_name: jagdgesellschaft-ai-web
    ports:
      - '6108:80'
      - '6443:443'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/certs:/etc/nginx/certs:ro
      - ./:/var/www/html

  # php
  app:
    user: www-data:www-data
    container_name: jagdgesellschaft-ai-app
    ports:
      - "6408:80"
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - ./.phpunit.cache:/var/www/html/.phpunit.cache
      - ./docker/php/usr/local/etc/php/conf.d/90-xdebug.ini:/usr/local/etc/php/conf.d/90-xdebug.ini
    env_file:
      - ./docker/docker.env